"""
This type stub file was generated by pyright.
"""

from typing import Any, Literal, Optional
from numpy import dtype, ndarray, uint8

def get_offset(hwnd: int) -> tuple[int, int]:
    ...

def get_image_by_rect(hwnd: int, x: int, y: int, method: Literal["srccopy", "windll"] = ..., width: Optional[int] = ..., height: Optional[int] = ...) -> ndarray[Any, dtype[uint8]]:
    ...

def get_image(hwnd: int, method: Literal["srccopy", "windll"] = ...) -> ndarray[Any, dtype[uint8]]:
    ...

